#!/usr/bin/env bash
docker run \
    --name z2m-basement \
    --network slacknet-0 \
    --ip=192.168.0.16 \
    --dns=192.168.0.13 \
    --restart=unless-stopped \
    --device=$(readlink -f dev):/dev/ttyACM0 \
    -v ./data:/app/data \
    -v /run/udev:/run/udev:ro \
    -e TZ=America/Chicago \
    -d \
    koenkk/zigbee2mqtt
